ka = 2; % wavenumber

% cylinder parameters
cylax = [0.5,0.5,1];    % cylinder axis
r = 2.5;                  % cylinder radius
%n = 20;                 % #pts on circle
L = 30; a = 1/2; b = 3/4; L0 = 10;      % complexification parameters

N = 10*round(2.^(1.5:0.5:6)/2);
Us = zeros(size(N));
Ud = zeros(size(N));
hh = zeros(size(N));
for ii = 1:numel(N)
    n = N(ii);
    s = cylinder_cmpl(cylax,r,L,n,a,b,L0);  % complexified cylinder

    % fix a target point
    i = 1+6*s.Nu/10;
    j = 1+34*s.Nu/10;
    ind = sub2ind([s.Nu,s.Nv],i,j);
    t.x = s.x(:,ind);

    % precompute correction weight (1-point)
    [Zs,Zd] = epstein_zeta_cmpl(1,s.E(ind),s.F(ind),s.G(ind),s.e(ind),s.f(ind),s.g(ind));
    Ds = s.w(ind)/(4*pi).*(-Zs/s.h + 1i*ka);
    Dd = Zd.*s.w(ind)/(4*pi*s.h);

    % evaluate potential
    sig = (sin(s.u+2) - 3*cos(0.7*s.v-pi)+1i*cos(2*s.u)*0.3.*s.v).*exp(-0.05*s.v.^2); % density
    A = Helm3dSLP_cmpl(ka,t,s); A(ind) = Ds; % slp
    u = A*sig(:);
    Us(ii) = u;
    A = Helm3dDLP_cmpl(ka,t,s); A(ind) = Dd; % dlp
    u = A*sig(:);
    Ud(ii) = u;
    hh(ii) = s.h; % mesh size

    % plot
    if n < 31
        clf
        subplot(1,3,1)
        x = real(t.x);
        plot3(x(1,:),x(2,:),x(3,:),'.r','markersize',20), hold on
        plot_surf(s,1), hold off
        axis([-10,5,-10,5,-15,5])
        legend('= target'), title('surface (real part)')
        
        % plot density
        subplot(1,3,2)
        plot_surf(struct('x',[s.u(:),s.v(:),sig(:)]','Nu',s.Nu,'Nv',s.Nv))
        title('density (real part)')
    end
end
err_s = abs(Us-Us(end));
err_d = abs(Ud-Ud(end));
subplot(1,3,3)
% err vs N
%loglog(N,err_s,'*',N,err_d,'o',N,1*N.^-3,'--','LineWidth',1), xlabel('$n$','Interpreter','latex')
% err vs h
loglog(hh,err_s,'*',hh,err_d,'o',hh,1e-3*hh.^3,'--','LineWidth',1), xlabel('$h$','Interpreter','latex') % ylim([8e-11,1e-2])
legend('SLP','DLP','$O(h^3)$','interpreter','latex','Location','northwest')
title('error')
%% annotations
annotation(gcf,'textbox',...
    [0.42 0 0.21 0.11],...
    'String','($\sigma = 0.0582-0.0192i$ at target)',...
    'LineStyle','none',...
    'Interpreter','latex',...
    'FontSize',14,...
    'FitBoxToText','off');
annotation(gcf,'textbox',...
    [0 0.0036871669307216 0.37 0.110687022900762],...
    'String','target $x=[-6.34- 0.035i, -5.788-0.035i, -8.637-0.0703i]$',...
    'LineStyle','none',...
    'Interpreter','latex',...
    'FontSize',14,...
    'FitBoxToText','off');

function plot_surf(s,wrap)
if nargin < 2, wrap = 0; end
Nr = [s.Nu,s.Nv];   % reshaping sizes
% note: assume grid generated by 'ndgrid'. If used 'meshgrid' then need to swap dim(x) and dim(y)!
x = reshape(real(s.x(1,:)),Nr);
y = reshape(real(s.x(2,:)),Nr);
z = reshape(real(s.x(3,:)),Nr);
if wrap
    x = x([1:end,1],:);
    y = y([1:end,1],:);
    z = z([1:end,1],:);
end
surf(x,y,z)
end
